# Utiliser la même base que l'API pour la cohérence
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .

# Installer les dépendances
RUN pip install uv && uv pip install --no-cache-dir --system -r requirements.txt

# Copier le code source nécessaire au worker
COPY ./worker.py .
COPY ./ai_analyzer.py .
COPY ./config ./config

# Commande pour lancer le worker au démarrage
CMD ["python", "worker.py"]