---
# Patch pour monter le ConfigMap des DAGs dans tous les déploiements Airflow
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  template:
    spec:
      volumes:
      - name: dags
        configMap:
          name: cgu-analysis-dag
      containers:
      - name: scheduler
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
          readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-dag-processor
  namespace: airflow
spec:
  template:
    spec:
      volumes:
      - name: dags
        configMap:
          name: cgu-analysis-dag
      containers:
      - name: dag-processor
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
          readOnly: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-api-server
  namespace: airflow
spec:
  template:
    spec:
      volumes:
      - name: dags
        configMap:
          name: cgu-analysis-dag
      containers:
      - name: api-server
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
          readOnly: true
