# Airflow Helm Values - Working Configuration
# Use KubernetesExecutor for pod-based task execution

executor: KubernetesExecutor

# PostgreSQL with latest tag
postgresql:
  enabled: true
  image:
    tag: latest

# Airflow webserver configuration
webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    password: admin
    email: admin@example.com

# Disable GitSync - use ConfigMap for DAGs
dags:
  gitSync:
    enabled: false

# Mount DAGs from ConfigMap
extraVolumes:
  - name: dag-volume
    configMap:
      name: airflow-dags

extraVolumeMounts:
  - name: dag-volume
    mountPath: /opt/airflow/dags
    readOnly: true
