# Airflow Helm Values Override
# This file configures persistent DAG storage using ConfigMap

# Use KubernetesExecutor (IMPORTANT!)
executor: KubernetesExecutor

# Use PostgreSQL (will use Helm chart default image)
postgresql:
  enabled: true

# Mount DAGs from ConfigMap instead of using ephemeral storage
dags:
  # Disable GitSync (we're using ConfigMap)
  gitSync:
    enabled: false

  # Configure DAG persistence via existing ConfigMap
  # The ConfigMap "airflow-dags" contains our DAG files
  persistence:
    enabled: false  # We're using ConfigMap, not PVC

# Add volume and volumeMount to mount the ConfigMap
extraVolumes:
  - name: dag-volume
    configMap:
      name: airflow-dags

extraVolumeMounts:
  - name: dag-volume
    mountPath: /opt/airflow/dags
    readOnly: true

# Configure static webserver secret key (fixes JWT authentication)
webserverSecretKeySecretName: airflow-webserver-secret
